### ISSUE TITLE
Spatial Structure for infra models

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/IFC4.x-IF#10]
This issue is for tracking agreements and comments on the use of Spatial Structure (SS) for IFC4.3

Here are the questions that triggered the discussion in the IF:
- Is there a fix (standard) spatial structure for infra models, like the one for buildings?
  - No, there is no fix spatial structure
- Does this mean that file federation cannot be based on SS?
  - Probably. Or at least not only on SS

The ones below are all example of legit SS:

**Example1**

> - IfcSite
>   - IfcRailway
>     - IfcRailwayPart (TRACK1)
>     - IfcRailwayPart (TRACK2)
>   - IfcBuilding
>   - IfcBuilding 
>   - IfcBridge

**Example2**

> - IfcSite
>   - IfcRailway
>     - IfcRailwayPart (TRACK1)
>     - IfcRailwayPart (TRACK2)
>     - IfcBuilding
>     - IfcBridge
>   - IfcBuilding 

**Example3**

> - IfcSite
>   - IfcRoad
>     - IfcRoadPart
>       - IfcRoadPart
>     - IfcRoadPart
>       - IfcRoadPart
>   - IfcBuilding
>   - IfcBuilding 
> - IfcSpazialZone (parcel or lot)

**Comment by JanErikHoel** [comment]
[IR-ROAD-WP3_ConceptualModelReport - Annex I - Example instance diagrams_2_0.docx](https://github.com/buildingSMART/IFC4.x-IF/files/9994353/IR-ROAD-WP3_ConceptualModelReport.-.Annex.I.-.Example.instance.diagrams_2_0.docx)

I believe this document should be the starting point for the discussion on the spatial breakdown for the road part of an infrastructure project. This is what we use as a guiding here at Trimble Norway.

**Comment by JanErikHoel** [comment]
We here in the Quadri team try to build up the correct spatial structure for a infrastructure project consisting of terrain, some roads and some water and sewer systems with their corresponding  alignments.

BUT in addition we have existing buildings, existing/planned trees etc. in the model (miscellaneous 2. order stuff).
How should we organize this in the spatial structure?

**Comment by SergejMuhic** [comment]
> * No, there is no fix spatial structure

I cannot help looking at this as an oxymoron. A structure not being fix? Well then it is not a structure and another concept should be used to represent it. The definition of structure:

"Something made up of a number of parts that are held or put together in a _**particular way**_."
