### ISSUE TITLE
Agreements on IfcAlignment and Spatial Structure

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/IFC4.x-IF#11]
**01**
Each IfcAlignment must be contained in an IfcSite

**02** (corollary of 01)
If a file has IfcAlignment, then cannot have 0 instance of IfcSite

**03**
If a file has IfcAlignment, then can have 1 or more instances of IfcSite

> (Example: one file can be the result of multiple merged files, each one with its own Site containing an Alignment. Meaning a file can have multiple Sites, all containing some Alignments)

![Image](https://user-images.githubusercontent.com/62438551/201349206-9bba76c1-f426-47cf-b937-a135110c2066.png)

Provide explanation if you think some of these agreements shall not be adopted. If you want, propose further agreements.

**Comment by JanErikHoel** [comment]
In a large/medium sized infrastructure project, we can typically have more than 100 alignments within one site
Some alignments are reference lines for the main road, local road, pedestrian roads etc, but many of these alignments are just "help alignments" to make nice "organic shaped" road edges at intersections etc..

If all alignments should be contained directly on the ifcSite, we need some possibility to group thee alignments,
