### ISSUE TITLE
IfcPolynomialCurve documentation needs improvement

### ISSUE THREAD

**Issue by RickBrice** [buildingSMART/IFC4.x-IF#129]
**Problem**
The documentation for [IfcPolynomialCurve](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcPolynomialCurve.htm) is lacking and there appears to be an error in the Formal propositions and Formal representation WHERE rule.

**Solution(s)**
See proposed documentation changes at https://github.com/buildingSMART/IFC4.3.x-development/issues/608

**Require schema changes?**
- ` ` yes
- `✓` no
- ` ` don't know

**Require documentation changes?**
- `✓ ` yes
- ` ` no
- ` ` don't know

**Rule required**
- `✓ ` normative check: every IFC file must pass this check
- ` ` good practice check: just triggers a warning, but the IFC file is still valid
- ` ` don't know

Change the `ValidCoefficients` rule from `(EXISTS(CoefficientsX) AND EXISTS(CoefficientsY)) OR (EXISTS(CoefficientsX) AND EXISTS(CoefficientsZ)) OR (EXISTS(CoefficientsY) AND EXISTS(CoefficientsZ)) OR (EXISTS(CoefficientsX) AND EXISTS(CoefficientsY) AND EXISTS(CoefficientsZ))` to `(EXISTS(CoefficientsX) AND EXISTS(CoefficientsY)) OR (EXISTS(CoefficientsX) AND EXISTS(CoefficientsY) AND EXISTS(CoefficientsZ))` so it is consistent with the `CorrectPositionDim` rule `((Position.Dim=2) AND (NOT EXISTS(CoefficientsZ))) OR (Position.Dim=3)`

**Comment by civilx64** [comment]
@RickBrice it sounds like this is a correction to a rule in the schema, not a new gherkin rule for the validation service - correct?

(Point of clarification: the schema rules are part of the validation service.)

@aothms - what are your thoughts?

**Comment by aothms** [comment]
I think so too, maybe that'd be a good clarification to the issue template to somehow distinguish between gherkin rules in the validation service and express rules in the schema.

**Comment by RickBrice** [comment]
@civilx64 Yes, I think correction in schema rule.

**Comment by evandroAlfieri** [comment]
[Issue template](https://github.com/buildingSMART/IFC4.x-IF/blob/main/.github/ISSUE_TEMPLATE/new-issue---proposal.md) modified.
@aothms being this a future schema change I'd close this issue...if you open a new one in the correct repo

**Comment by aothms** [comment]
https://github.com/buildingSMART/IFC4.3.x-development/issues/608#issuecomment-1826253120
