### ISSUE TITLE
Documentation Question - "The entity is not part of a standardized schema subset or implementation level"

### ISSUE THREAD

**Issue by gmn3DS** [buildingSMART/IFC4.x-IF#132]
Hello,

I have stumbled across the following note in the documentation.
![image](https://github.com/buildingSMART/IFC4.x-IF/assets/124370855/b64d5894-1026-4ad0-a379-04378a4fd555)

So far, I have seen it written on the following entities:

- **[IfcRelProjectsElement](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcRelProjectsElement.htm)**
- **[IfcCsgSolid](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcCsgSolid.htm)**

However both entities can be found in IFC2x3 and IFC4 ISO express [schemas](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/).

Is the note misleading or should these entities not be implemented?
If the latter, is there a complete list of concerned entities?

Best regards,
Guillaume

**Comment by aothms** [comment]
In the alphabetical listing you can see to which entities this applies https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/annex-b1.html (i.e the ones that do not have AbRV/RV/product next to it.

For a considerable time there was a stronger separation between the specification as published and the ability to compose arbitrary model view definitions that could be freely select items to be in scope for certain exchanges. https://www.buildingsmart.org/the-curious-case-of-the-mvd/

Nowadays there is an effort to standardize also more on this MVD level to reduce incompatibilities and incorporate more of this MVD context into the documentation.

The standardized MVDs are rather limited though in their expressiveness. Reference View is intended as a reference and not a full exchange of the design intent (things are bit different in building domain vs infra). Therefore things like additive modelling, feature based modelling and BReps with underlying curved surface geometry is indeed out of scope.

MVDs have not been rigorously implemented in the majority of the software though. Things outside of the RV MVDs will likely be successfully imported in a number of cases.

**Comment by gmn3DS** [comment]
Thanks Thomas for your detailed explanations.

MVDs didn't immediately appear in my mind when reading the note...
It is now clear :)
