### ISSUE TITLE
Consistent type for .Segments attribute of IfcCompositeCurve (and subtypes)

### ISSUE THREAD

**Issue by civilx64** [buildingSMART/IFC4.x-IF#137]
**Problem**

The IFC 4.3 specification is unclear.  See comment in buildingSMART/validate#7 by @RickBrice.

**Solution(s)**

I believe that a validation rule is required, but I would like to gather consensus on the details of the rule.  Also I would need to know if this should be documented as an implementer agreement or informal proposition.  (My hunch is the latter.)

**Require schema changes?**
- ` ` yes
- `✓` no
- ` ` don't know

**Require documentation changes?**
- ` ` yes
- ` ` no
- `✓` don't know

**Rule required**

- `✓` normative check: every IFC file must pass this check
- ` ` good practice check: just triggers a warning, but the IFC file is still valid
- ` ` don't know

At minimum the validation rule should probably enforce a consistent type for all of the `Segments` - no mixing or matching.  The rule might also enforce the use of type `IfcSegment`.

**Additional context**

- `IfcCompositeCurve` can technically be composed from segments of type `IfcSegment` and `IfcCompositeCurveSegment`.

- Per CT 4.1.7.1.1, `IfcCurveSegment` appears to be the only valid type to be used for the `.Segment` property of `IfcCompositeCurve` and subtypes when used for representation of alignments,

- Subtypes of `IfcCompositeCurve` are `IfcSegmentedReferenceCurve`, `IfcGradientCurve`, and `IfcCompositeCurveOnSurface`.
- IFC 4.0.2 requires `IfcCompositeCurve.Segment` to be of type `IfcCompositeCurveSegment`. Is the change in IFC 4.3 intentional?

I'm guessing a bit on audience targeting but suspect that @aothms, @evandroAlfieri, and @peterrdf are a good place to start.

**Comment by aothms** [comment]
> Per CT 4.1.7.1.1, IfcCurveSegment appears to be the only valid type to be used for the .Segment property of IfcCompositeCurve and subtypes when used for representation of alignments,

I think alignment representations as simple polylines is also condoned. from that point of view it would make sense to also allow the regular STEP brother (haha) IfcCompositeCurveSegment for an alignment representation.

I think the following rules make sense:

- Uniform segment type
- IfcSegmentedReferenceCurve/IfcGradientCurve require IfcCurveSegment

**Comment by civilx64** [comment]
Added to validation rules backlog as ALS011, being tracked at buildingSMART/ifc-gherkin-rules#129

**Comment by evandroAlfieri** [comment]
closing this one, due to the validation rule's one. Good catch
