### ISSUE TITLE
Helmert Transition Segment

### ISSUE THREAD

**Issue by RickBrice** [buildingSMART/IFC4.x-IF#143]
I'm confused by the Helmert Transition Segment. For now, let's keep this strictly to horizontal alignment geometry. I want to compute (X,Y) and tangent along the curve segment.

## Is an IfcSecondOrderPolynomialSpiral always a two-part "mirrored" curve?

From the Partial Concept Template [4.2.2.2.6](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Helmert_Transition_Segment/content.html), we see that the IfcCurveSegment.ParentCurve is an IfcSecondOrderPolynomialSpiral. The description talks about the Quadratic term for the first half and Quadratic, Linear, and Constant terms for the second half.

![image](https://github.com/buildingSMART/IFC4.x-IF/assets/37087370/7f02d4eb-601d-48d9-843b-73f093cde688)

Should I expect a consecutive pair of IfcCurveSegment with ParentCurve = IfcSecondOrderPolynomialSpiral for each IfcAlignmentHorizontalSegment with PredefinedType = HELMERTCURVE? The first IfcCurveSegment would be the "first half" and the second the "second half". This doesn't seem to be the intent.

If the intent is a single IfcCurveSegment.ParentCurve = IfcSecondOrderPolynomialSpiral for each IfcAlignmentHorizontalSegment.PredefinedType = HELMERTCURVE, then are all IfcSecondOrderPolynomialSpiral entities to be interpreted as a two-part curve? I don't see anything in the documention for IfcSecondOrderPolynomialSpiral, [8.9.3.60](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcSecondOrderPolynomialSpiral.htm), that would indicate this curve is to be treated differently from the other IfcThird... and IfcSeventhOrderPolynimalSpiral entities.

## Documentation Error?
[4.2.2.2.6](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Helmert_Transition_Segment/content.html) says "*SegmentStart* is the **bearing angle** at start and *SegmentLength* is the **bearing angle** at the end of the segment". However, the IfcCurveSegment.SegmentStart and IfcCurveSegment.SegmentLength are of type IfcCurveMeasureSelect, which by the informal proposition of [8.9.3.28.1](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcCurveSegment.htm), must be IfcLengthMeasure. The figure also indicates IfcLengthMeasure.

Note also that Bloss Transition Segment [4.2.2.2.2](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Bloss_Transition_Segment/content.html) and Viennese Bend Transition Segment [4.2.2.2.10](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Viennese_Bend_Transition_Segment/content.html) do not make any statements about the SegmentStart and SegmentLength attributes.

Is this statement in error and should it be removed from the documentation?

**Comment by RickBrice** [comment]
I found the following in @peterrdf presentation - it answers my first question - one business logic Helmert curve maps into two geometry curves.
![image](https://github.com/buildingSMART/IFC4.x-IF/assets/37087370/a31f4970-2e7c-4e82-aa63-53373d32f46a)

**Comment by civilx64** [comment]
@RickBrice are there any other predefined types where this is the case?  This will affect the alignment rules being developed for the validation service.  Currently there is a check of number of segments in the business logic and the representation to confirm the same number of total segments in both.  But based on your feedback, a single Helmert curve segment corresponds to two curves in the geometry, which means that some additional nuance will be needed in the implementation of validation rule ALA002.

**Comment by RickBrice** [comment]
@civilx64 as far as I know, this is the only case. I don't know if it is a strict rule or not. This is just my conclusion based on observation. The examples from the [RailRoom](https://github.com/bSI-RailwayRoom/IFC-Rail-Sample-Files/tree/main/1_Alignment%20with%20Cant%20(AWC)/UT_AWC_0_(Synthetic_Cases)/Horizontal/SyntheticTestcases/Helmert ) seem to have 2 geometry for 1 business logic helmert curve segment. Perhaps [4.2.2.2.6](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Helmert_Transition_Segment/content.html) needs to illustrate this.

**Comment by civilx64** [comment]
Thanks, I reviewed the docs for segment type enumerations and came to the same conclusion. I will revise ALA002 accordingly.

**Comment by aothms** [comment]
What would the representation of that segment be then? The individual
segments on the business logic side point to one of the constituents within
the comp curve I thought.

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op do 22 feb. 2024 15:21 schreef Scott Lecher ***@***.***>:

**Comment by RickBrice** [comment]
Not sure if this answers your question but the IfcCompositeCurve is a representation at the level of IfcAlignment, which is just a collection of IfcCurveSegments.

At the IfcCurveSegment level, the 'Axis' 'Segment' representation is a representation context referencing two IfcCurveSegments.

Here is an example taken from the Rall Room. See `#55`

~~~
ISO-10303-21;
HEADER;
FILE_DESCRIPTION (('ViewDefinition [CoordinationView]'), '2;1');
FILE_NAME ('Single-LANDXML.ifc', '2021-05-24T11:00:00', ('IFC Rail Technical Services'), ('buildingSMART International RailwayRoom'), 'RailCOMPLETE\X2\FFAE\X0\', '2019.1.1995.0', '');
FILE_SCHEMA (('IFC4X3_ADD2'));
ENDSEC;
DATA;
#1 = IFCPROJECT('1FNFy8AJeHwwz7wDZHIYIu', #3, 'IFC Rail Referencedata', 'Rail alignment sample', $, 'Longname', 'Design', $, #9);
#2 = IFCAPPLICATION(#5, '2019.1.1995.0', 'RailCOMPLETE\X2\00AE\X0\', 'Unknown');
#3 = IFCOWNERHISTORY(#6, #2, $, $, $, $, $, 999999);
#4 = IFCPERSON('TS', 'IFC Rail Technical Services', $, $, $, $, $, $);
#5 = IFCORGANIZATION('bsI RWR', 'buildingSmart International Railway Room', $, $, $);
#6 = IFCPERSONANDORGANIZATION(#4, #5, $);
#7 = IFCSIUNIT(*, .LENGTHUNIT., $, .METRE.);
#8 = IFCSIUNIT(*, .PLANEANGLEUNIT., $, .RADIAN.);
#9 = IFCUNITASSIGNMENT((#7, #8));
#10 = IFCCARTESIANPOINT((0., 0., 0.));
#11 = IFCDIRECTION((0., 0., 1.));
#12 = IFCDIRECTION((1., 0., 0.));
#13 = IFCAXIS2PLACEMENT3D(#10, #11, #12);
#14 = IFCLOCALPLACEMENT($, #13);
#15 = IFCRAILWAY('1FNFy9AJeHwuVmwDZHIYIu', #3, 'optional Railway Name', 'optional Railway Description', $, #14, $, 'Longname for Railway track geometry (alignment)', $, $);
#16 = IFCDIRECTION((0., 1.));
#17 = IFCGEOMETRICREPRESENTATIONCONTEXT($, 'MODEL', 3, 1.E-5, #13, #16);
#18 = IFCRELAGGREGATES('1FNFyAAJeHwu6TwDZHIYIu', #3, 'Documentation Container', 'Container for IfcProject, collects relevant products', #1, (#15));
#19 = IFCRELCONTAINEDINSPATIALSTRUCTURE('1FNFyBAJeHwvmywDZHIYIu', #3, 'IfcProducts contained in myIfcRailway', 'Association between IfcProducts and IfcRailway', (#20), #15);
#20 = IFCALIGNMENT('1FNFyCAJeHwxedwDZHIYIu', #3, 'Spor', 'optional Railway Description', $, #63, #66, $);
#21 = IFCALIGNMENTHORIZONTAL('1FNFyDAJeHwv87wDZHIYIu', $, $, $, $, #68, #71);
#28 = IFCCARTESIANPOINT((0., 0.));
#29 = IFCALIGNMENTHORIZONTALSEGMENT($, $, #28, 0., 0., 300., 100., $, .HELMERTCURVE.);
#30 = IFCALIGNMENTSEGMENT('1FNFyHAJeHwuDtwDZHIYIu', #3, $, $, $, #51, #54, #29);
#34 = IFCRELNESTS('3BxjiarjCHwuiObERtTLTf', $, $, $, #21, (#30));
#35 = IFCRELNESTS('3BxjiYrjCHwwCwbERtTLTf', $, $, $, #20, (#21));
#36 = IFCCOMPOSITECURVE((#37, #50), .F.);
#37 = IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE., #43, IFCLENGTHMEASURE(0.), IFCLENGTHMEASURE(50.), #46);
#38 = IFCLOCALPLACEMENT($, #39);
#39 = IFCAXIS2PLACEMENT3D(#40, $, $);
#40 = IFCCARTESIANPOINT((0., 0., 0.));
#43 = IFCAXIS2PLACEMENT2D(#44, #45);
#44 = IFCCARTESIANPOINT((0., 0.));
#45 = IFCDIRECTION((1., 0.));
#46 = IFCSECONDORDERPOLYNOMIALSPIRAL(#47, 1224.74487139159, $, $);
#47 = IFCAXIS2PLACEMENT2D(#48, #49);
#48 = IFCCARTESIANPOINT((0., 0.));
#49 = IFCDIRECTION((1., 0.));
#50 = IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE., #56, IFCLENGTHMEASURE(50.), IFCLENGTHMEASURE(50.), #59);
#51 = IFCLOCALPLACEMENT($, #52);
#52 = IFCAXIS2PLACEMENT3D(#53, $, $);
#53 = IFCCARTESIANPOINT((0., 0., 0.));
#54 = IFCPRODUCTDEFINITIONSHAPE($, $, (#55));
#55 = IFCSHAPEREPRESENTATION(#17, 'Axis', 'Segment', (#37,#50));
#56 = IFCAXIS2PLACEMENT2D(#57, #58);
#57 = IFCCARTESIANPOINT((49.9972443634885, 3.47204361427475E-1));
#58 = IFCDIRECTION((9.99614222337484E-1, 2.77742056705088E-2));
#59 = IFCSECONDORDERPOLYNOMIALSPIRAL(#60, -1224.74487139159, 7500., -3.33333333333333E-3);
#60 = IFCAXIS2PLACEMENT2D(#61, #62);
#61 = IFCCARTESIANPOINT((1.15725277555399E-2, -6.942977411122E-1));
#62 = IFCDIRECTION((9.98457186998745E-1, 5.55269820047339E-2));
#63 = IFCLOCALPLACEMENT($, #64);
#64 = IFCAXIS2PLACEMENT3D(#65, $, $);
#65 = IFCCARTESIANPOINT((0., 0., 0.));
#66 = IFCPRODUCTDEFINITIONSHAPE($, $, (#67));
#67 = IFCSHAPEREPRESENTATION(#17, 'Axis', 'Curve2D', (#36));
#68 = IFCLOCALPLACEMENT($, #69);
#69 = IFCAXIS2PLACEMENT3D(#70, $, $);
#70 = IFCCARTESIANPOINT((0., 0., 0.));
#71 = IFCPRODUCTDEFINITIONSHAPE($, $, (#72));
#72 = IFCSHAPEREPRESENTATION(#17, 'Axis', 'Curve2D', (#36));
ENDSEC;
END-ISO-10303-21;
~~~

**Comment by apinzenoehler** [comment]
The two halfs for HELMERT are a result of the two distinct curvature functions for the first and the second half of a HELMERT transition bend. As others already noted HELMERT is the only transition bend supported in Ifc 4.3 with a split curvature function.

In Ifc 4.3 documentation an explanation can be found at https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcAlignmentHorizontalSegmentTypeEnum.htm.

This curvature transition was proposed first by Friedrich Helmert in 1873. According to some sources HELMERT transition bends were in use by Deutsche Bahn in the past. It is still used in Finland and possibly also in Sweden.

Therefore the HELMERT transition bend is included in European Norm 13803. 

A note for readers interested in technical history: 

Before the availablity of computing devices HELMERT transition bends were approximated by the biquadratic parabola, as no economically viable calculation methods with good accuracy were available.

**Comment by aothms** [comment]
Thanks. I guess an alternative would be / would have been to wrap both
curves within that pair in a an additional composite curve, nested within
the main composite curve (I didn't verify how well that works). As I can
imagine that unsuspecting implementers would assume an index into the
business logic segments corresponds to an index on the composite curve
segments. Currently that would violate the 'Segment' RepresentationType
though.


Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op do 22 feb. 2024 20:13 schreef apinzenoehler ***@***.***>:

**Comment by peterrdf** [comment]
I didn't think it through totally however my first feedback on this idea would be that currently each IfcCurveSegment.ParentCurve is an unbounded curve (not by definition however). Making a nested structure (and therefore introducing bounded curves for parent curves) could introduce tricky issues especially as tangent (and in some cases even second order direction / tangent) at least the end points of the clipped curves are relevant.

**Comment by civilx64** [comment]
> Also note that technically there could be more cases where an IfcAlignmentSegment has other than exact one IfcCurveSegment related. For example the case where it represents the last zero length element; in case of vertical and cant alignment this knowledge could be represented in EndPoint of IfcGradientCurve and IfcSegmentedReferenceCurve, although to my knowledge we agreed not to use EndPoint's in this case but to create a 0-length IfcCurveSegment in line with IfcCompositeCurve that does not have this EndPoint attribute. As a consequence it could also happen that IfcCurveSegment exists that do not have an IfcAlignmentSegment counterpart as the zero length last element was not defined.

I respectfully disagree with these possible additional cases. The [concept template for alignment segments](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/concepts/Product_Shape/Product_Geometric_Representation/Alignment_Geometry/Alignment_Geometry_-_Segments/content.html) states that a zero-length segment must be present as the final IfcAlignmentSegment for horizontal, vertical and cant.  Furthermore it states that each zero-length IfcAlignmentSegment must have a corresponding zero-length curve segment.

Net result is that a Helmert segment is the only case where one IfcAlignmentSegment is represented by more than 1 curve segment - and it must be represented by exactly 2 segments per discussion upstream.

**Comment by peterrdf** [comment]
Although theoretically you are correct, it depends on the purpose of use. For example in our case as a library provider we will need to support different situations, especially in case no schema violation is triggered when implementing the last zero-length segment differently or completely omit it. My expectation is that several IFC file providers will produce technically indeed still incorrect files that however are fully in accordance with the schema itself. I know there are discussions if it is correct to support incorrect data, however for now we keep trying to support as much cases as possible.

**Comment by apinzenoehler** [comment]
> Net result is that a Helmert segment is the only case where one IfcAlignmentSegment is represented by more than 1 curve segment - and it must be represented by exactly 2 segments per discussion upstream.

Looking at the regulations which were the basis for IFC alignment requirements I think it is possible to define the proposed constraint of an one to one association of alignment business definition and IFC-geometry representation.

But please keep in mind that the regulations cover only the rules for the participating rail infrastructure managers and also keep in mind that only the prioritized processes were considered.

A nice example of such deliberations can be found at https://github.com/bSI-RailwayRoom/IFC-Rail-Unit-Test/issues/52#issuecomment-743193952.

This "doucine" issue from 2020/2021 was closed in January 2021 because French SNCF decided that the detailed representation of doucine was not required in a first IFC version for rail.

In case the quoted decision would have been otherwise very possible there would be another geometric representation. One business segment would then possibly be represented by three IFC geometry segments to model the smoothing logic of the doucine.

If the validation rule proposal is meant to safeguard a "minimum average" of trackgeometry designs then please go ahead. As long as there are options for implementing more sophisticated designs with alternative IFC geometry representations I see no issue.

However if the validation rule proposal is meant to define a constraint for all potential cases I would strongly object to the rule. I would see no benefit to restrict the applicability of IFC to more sophisticated track geometry designs without real necessity.

**Comment by civilx64** [comment]
> For example in our case as a library provider we will need to support different situations, especially in case no schema violation is triggered when implementing the last zero-length segment differently or completely omit it. 

Very good point... from this perspective there is a need to be more flexible in what is accepted as valid input, compared to what the validation service identifies as pass / fail.

**Comment by RickBrice** [comment]
Is there a document error?

[4.2.2.2.6](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Helmert_Transition_Segment/content.html) says "SegmentStart is the bearing angle at start and SegmentLength is the bearing angle at the end of the segment". However, the IfcCurveSegment.SegmentStart and IfcCurveSegment.SegmentLength are of type IfcCurveMeasureSelect, which by the informal proposition of [8.9.3.28.1](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcCurveSegment.htm), must be IfcLengthMeasure. The figure also indicates IfcLengthMeasure.

Note also that Bloss Transition Segment [4.2.2.2.2](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Bloss_Transition_Segment/content.html) and Viennese Bend Transition Segment [4.2.2.2.10](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Viennese_Bend_Transition_Segment/content.html) do not make any statements about the SegmentStart and SegmentLength attributes.

Is this statement in error and should it be removed from the documentation?

**Comment by RickBrice** [comment]
@civilx64 @peterrdf @aothms @apinzenoehler 

Would another case where one business logic definition (IfcAlignmentHorizontalSegment) map into two geometric representations (IfcCurveSegment) be a S-curve or reverse curve?

This situation would occur for an IfcAlignmentHorizontalSegment where .StartRadiusOfCurvature and .EndRadiusOfCurvature have opposite signs, meaning one is CCW and one is CW.

**Comment by civilx64** [comment]
Per my understanding, no. 

LINEAR segments require start and end radius to be 0.  CIRCULARARC segments require start and end radius to be the same magnitude and same sign. Assuming you are thinking of an S-curve as two back-to-back arcs, that situation would require two logic segments, each with a corresponding representation segment.

This leaves transition curves as the only PredefinedType that could have start and end radius of different sign. With the exception of HELMERTCURVE previously discussed this transition segment would have a single representation.

**Comment by RickBrice** [comment]
@civilx64 I think you are right. With a transition curve in an S-shape it would have start and length with opposite signs and length would be of sufficient magnitude to cause the curve to go through the origin and beyond.

**Comment by evandroAlfieri** [comment]
@RickBrice @civilx64 @aothms did you reach a conclusion? Namely, I'm interested in one or more of these: change in documentation, creation of validation service rules. Do you have proposals for any of these?

**Comment by RickBrice** [comment]
I think we got things figured out that the Helmert curve will have a 1:2 mapping from business to geometry. I don't think any documentation changes are needed for that per se, but stating it explicitly in plain language might be helpful in the future.

There remains an open question about the documentation, copied from above

> Documentation Error?
> [4.2.2.2.6](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Helmert_Transition_Segment/content.html) says "SegmentStart is the bearing angle at start and SegmentLength is the bearing angle at the end of the segment". However, the IfcCurveSegment.SegmentStart and IfcCurveSegment.SegmentLength are of type IfcCurveMeasureSelect, which by the informal proposition of [8.9.3.28.1](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcCurveSegment.htm), must be IfcLengthMeasure. The figure also indicates IfcLengthMeasure.
> 
> Note also that Bloss Transition Segment [4.2.2.2.2](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Bloss_Transition_Segment/content.html) and Viennese Bend Transition Segment [4.2.2.2.10](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Partial_Templates/Geometry/Curve_Segment_Geometry/Viennese_Bend_Transition_Segment/content.html) do not make any statements about the SegmentStart and SegmentLength attributes.
> 
> Is this statement in error and should it be removed from the documentation?

**Comment by civilx64** [comment]
This is already covered in the validation rules that have been created thus far, so no additional rules required at this time.

**Comment by civilx64** [comment]
> This is already covered in the validation rules that have been created thus far, so no additional rules required at this time.

Deployed in v0.6 of [Validation Service](https://validate.buildingsmart.org)

1. [ALS010](https://github.com/buildingSMART/ifc-gherkin-rules/blob/development/features/ALS010_Alignment-segment-shape-representation-has-the-correct-number-of-items.feature)
