### ISSUE TITLE
Provide valid EXPRESS encoding for this WKT literal

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/IFC4.x-IF#15]
I've just created a sample file using the _IfcWellKnownText_, to show its use in a georeferencing scenario - with IFC4.3_ADD1.
To facilitate reading the example, for now, I kept the outlook and indent of the WKT literal.
However, as we know, text in a STEP file must be encoded, so characters such as / should be escaped, newlines get serialized as 33N",\X2\000A\X0\, and so on.

Can anyone edit the part of the file linked below, to make it correct form STEP syntax point of view?
@jmirtsch

https://github.com/buildingSMART/IFC4.x-IF/blob/06d50cfaea840e9932ac29cd7262a3f4ff2ead2b/IFC-files/Georeferencing/Georeferencing_COMPDCS(WKT)-RO.ifc#L914-L945

**Comment by aothms** [comment]
Actually there is a bit of nuance here. Let me muddy the waters a bit.

### On newlines:

---

**5.6 Token separators**

> NOTE Space is the only whitespace character that separates tokens. Line-delimiters such as line feed or carriage return and other control characters such as form feed or character tabulation (tab) may appear in the exchange structure but are required by 5.2 to be ignored when processing the exchange structure. Consequently, line breaks may appear anywhere within the structure, including within tokens.

---

There are also print control directives:

---

> Explicit print control directives are also allowed within strings. The directives "\N\" and "\F\" do not contribute to the effective contents of the string. For the encoding of strings see 6.4.3. The print control directives "\N\" and "\F\" are relevant only for the printed presentation of the exchange structure and are to be ignored otherwise. Annex G provides guidance on the printing of the exchange structure.

---

This is one of the more annoying confusing aspects of the standard. I though we had an implementer agreement to make this behaviour a bit less crazy but I can't find it.

So to summarize:

- Three different kind of newlines:
  - Textual ascii line breaks (as in your example now) which **must** be ignored when parsing, but are **valid**
  - Newlines that are meant to survive import `\X2\000A\X0`. 
  - Print control directives (for people interested in typesetting p21 files in books? only god knows).

I don't know which toolkits support arbitrary textual line breaks (I wouldn't risk it). My proposal would be:

- Remove all unnecessary whitespace from the WKT string in the entity instance.
- Supply a nicely formatted WKT in a comment for humans (`/* ... */`) 

### On special characters:

`/` (forward slash) is fine actually. Only `\` (backslash; called reverse solidus in p21 and unicode) needs to be encoded.

```
STRING            = "'" { SPECIAL | DIGIT | SPACE | LOWER | UPPER | 
                    APOSTROPHE APOSTROPHE | 
                    REVERSE_SOLIDUS REVERSE_SOLIDUS | 
                    CONTROL_DIRECTIVE } "'" .

SPECIAL  = "!" | """" | "*" | "$" | "%" | "&" | "." | "#"
	 | "+" | ","  | "-" | "(" | ")" | "?" | "/" | ":" 
	 | ";" | "<"  | "=" | ">" | "@" | "[" | "]" | "{" 
	 | "|" | "}"  | "^" | "`" | "~" .
```

**Comment by evandroAlfieri** [comment]
@aothms very detailed answer, thanks!
02d6a380b9e5a4db13e91cec85e90fdac6d4edae could this work?
