### ISSUE TITLE
ACCA_sleepers-linear-placement-cant-implicit.ifc renders differently

### ISSUE THREAD

**Issue by aothms** [buildingSMART/IFC4.x-IF#151]
**Problem**

@michelangelo-acca 

Thanks for all the great work on sample files and implementations. It really helps move industry further. However, I noticed that when I upload ACCA_sleepers-linear-placement-cant-implicit.ifc to usBIM online it renders wrongly. Seems like the tilt vector gets mirrored for the sleepers vs rail respectively. There aren't a lot of example models with combinations of cant, sweep and placement. Would be really interested in knowing whether the issue is in model or implementation. Thanks again.

![afbeelding](https://github.com/buildingSMART/IFC4.x-IF/assets/1096535/4996b892-863b-4363-8c9a-cef2ae9a9dc3)

**Comment by peterrdf** [comment]
Hi @aothms, could you share this example file here, I can have a look. Cheers, Peter.

**Comment by aothms** [comment]
Thanks Peter, I meant this one: https://github.com/buildingSMART/IFC4.x-IF/blob/main/IFC-files/Linear-placement-sleepers/ACCA/ACCA_sleepers-linear-placement-cant-implicit.ifc

**Comment by michelangelo-acca** [comment]
Definitely need to have a closer inspection at this one 😳

**Comment by aothms** [comment]
@peterrdf any updates on this? :)

**Comment by peterrdf** [comment]
Just fixed, see https://[rdf.bg/product-list/ifc-engine/ifc-viewer/](https://rdf.bg/product-list/ifc-engine/ifc-viewer/)

**Comment by michelangelo-acca** [comment]
We have updated the IFC model but the bSI Validation Service is still giving the same error...is the service not up-to-date yet?

**Comment by evandroAlfieri** [comment]
If you're talking about ALA003 rule, it's been fixed but the plan is to deploy in 2 weeks (waiting for other ongoing fixes). I'll keep you posted (or you can activate notifications [here](https://forums.buildingsmart.org/t/validation-service-updates/4992/)).

**Comment by michelangelo-acca** [comment]
Subscribed. The file now shows correctly on [usBIM](https://cloud.usbim.com/)!

**Comment by michelangelo-acca** [comment]
Updated in #163 now visualizing correctly on usBIM and compliant with bSI Validation Service 0.6.5
