### ISSUE TITLE
IFC4X3_ADD2 - Typos in ISO Components

### ISSUE THREAD

**Issue by gmn3DS** [buildingSMART/IFC4.x-IF#153]
Hello,

I was writing some files in IFC4X3_ADD2 and noticed what I think could be some typos in the official documentation, which is probably generated from the official ISO components: Express/XSD/XMLs. 

I don't know if they have already been logged in so I'm reporting them here.
(Sorry for not seeing them earlier and/or duplicating a topic if it exists :( )

### [IFCMARINEPART/GUDINGSTRUCTURE](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcMarinePartTypeEnum.htm)
![image](https://github.com/buildingSMART/IFC4.x-IF/assets/124370855/629ab9f9-159f-449f-9e5f-3ccb96e89766)

Predefined type "GUDINGSTRUCTURE" should be called **"GUIDINGSTRUCTURE"**.

### [Pset_SolidStratumCapacity/PoisonsRatio](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/Pset_SolidStratumCapacity.htm)
![image](https://github.com/buildingSMART/IFC4.x-IF/assets/124370855/fe5e4d6c-7d22-4339-bc10-6b43360f239e)

Property "PoisonsRatio" should be called **"PoissonsRatio"**

### [Pset_MooringDeviceCommon/MinumumLineSlope](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/Pset_MooringDeviceCommon.htm)
![image](https://github.com/buildingSMART/IFC4.x-IF/assets/124370855/ca289b43-de23-4a10-8a9f-7e8290995939)

Property "MinumumLineSlope" should be called **"MinimumLineSlope"**

Best Regards,
Guillaume

**Comment by evandroAlfieri** [comment]
Thanks @gmn3DS for reporting these typos. And I'm afraid there might be more. Unfortunately, these kinds of changes can only be made in the next major release of the standard - where breaking compatibility is allowed. For now, as ugly as they look, we shall live with them. The (small) consolation is that the descriptions make clear what the indented functionality is.

**Comment by berlotti** [comment]
In the end this is a 'computer interpretable' standard. The name/code can be anything. It could be 'IFC654'. Other standards  split 'code' and 'name' in a better way (EC011690 for a pump in ETIM for example). 

As long as a computer knows how to handle it the naming of the code doesn't really matter.
We created codes that have meaning for humans which we perceive as typos.... a computer doesn't care.

That said; making the point; yes... it needs to be fixed in the next major release :-)

**Comment by aothms** [comment]
... and for 4.4 we really need implement some form of spelling check. I propose to have attribute / prop names in a human readable form in UML. So `GUDINGSTRUCTURE` -> `guiding structure` and have the formatting applied when serializing to express with different rules for enum / prop names etc. That's the only way we can have spell checking basically. I agree it doesn't realistically hinder interoperability except when people start handwriting things in export mappings or IDS'es, but it really affects the perceived quality of the standard.
