### ISSUE TITLE
Add IFC++ to list of IFC SDKs

### ISSUE THREAD

**Issue by thbeu** [buildingSMART/IFC4.x-IF#155]
IFC++ (available from https://github.com/ifcquery/ifcplusplus) is missing in the list of SDKs.

**Comment by evandroAlfieri** [comment]
I've just invited you to the repository. Feel free to make a pull request with the new entry for IFC++. Thanks!

**Comment by thbeu** [comment]
> @thbeu any news on this?

I am not affiliated with IFC++ and only wanted to raise this missing SDK.

> I've just invited you to the repository. Feel free to make a pull request with the new entry for IFC++. Thanks!

PRs are always possible even for any GH members.

**Comment by evandroAlfieri** [comment]
I see. @ifcquery care to add your entry to the table?

**Comment by ifcquery** [comment]
Hi, yes that would be great!
Let me know if you need any infos.
Thanks!

**Comment by evandroAlfieri** [comment]
Great! Just issue a PR with your entry added to the table at the end of this [readme](https://github.com/buildingSMART/IFC4.x-IF/blob/main/README.md#list-of-sdk-supporting-ifc43-add2)
