### ISSUE TITLE
IfcClothoid parameterization

### ISSUE THREAD

**Issue by RickBrice** [buildingSMART/IFC4.x-IF#165]
There seems to be some differences in how implementers are interpreting the parameterization of an IfcClothoid. The question came up in this post https://github.com/IfcOpenShell/IfcOpenShell/issues/5418.

You can clearly see in the screenshots the differences in implementation.

My basic question is this: Is the IfcClothoid documentation correct?

Based on the official IFC 4x3 ADD 2 schema definition, I think IfcOpenShell has the geometry of [8.9.3.19 IfcClothoid](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcClothoid.htm) implemented correctly - but I'm totally open to the idea that I've got something wrong.

Specifically, u is a parameter value and s is an arc length
![image](https://github.com/user-attachments/assets/87cec1fa-6c78-4bd2-96eb-631609a8d1bd)

From the Route43.ifc file the two "incorrect" looking curve segments are, 
~~~
#131= IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE.,#132,IFCPARAMETERVALUE(-30.),IFCNONNEGATIVELENGTHMEASURE(30.),#135);
#135= IFCCLOTHOID(#136,94.868329805051374);

#191= IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE.,#192,IFCPARAMETERVALUE(-50.),IFCNONNEGATIVELENGTHMEASURE(50.),#195);
#195= IFCCLOTHOID(#196,-122.47448713915891);
~~~

Considering `#131 IfcCurveSegment`, the start of the curve is at a parameter value of -30.

The length of the curve from the origin to the start point is then $s = Au\sqrt\pi = (94.868)(-30.0)\sqrt\pi = -5044.47$

The curve segment progresses from that point forward by 30 units. 

At -5044.47 from the origin is where the spiral is looping back around itself rapidly. This is why the curve segment looks like a corkscrew.

If the intent is to start the spiral at -30 units from the origin, the correct parameter value should be $-30 = (94.868)u\sqrt\pi$ so $u = -0.1784$

Based on the screenshots in the referenced post, clearly all implementers are not interpreting the parameterization of a clothoid in the same way.

**Comment by peterrdf** [comment]
The example files look relatively old and created against an older IFC4.3 schema, see for example line:
#131= IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE.,#132,IFCPARAMETERVALUE(-30.),IFCNONNEGATIVELENGTHMEASURE(30.),#135);
IFCNONNEGATIVELENGTHMEASURE should be IFCLENGTHMEASURE if we follow the latest schema and in principle IFCPARAMETERVALUE's are not allowed, especially combining IFCPARAMETERVALUE and IFCLENGTHMEASURE is something I would not be in favor of.

Note that usBIM is based on our RDF library and therefore usBIM and RDF IFC Viewer will show similar results.

Also note that the underlying library does support IFCPARAMETERVALUE for IfcClothoid, however recognizes corner cases and handles them differently; so these 'out of the ordinary' values as available in the example file could trigger this mechanism and show seemingly good results eventhough Ifc Open Shell could actually show the expected results based on the schema; while both libraries act the same on 'normal' data. My expectation that is the case here.

**Comment by RickBrice** [comment]
> Ifc Open Shell could actually show the expected results based on the schema; while both libraries act the same on 'normal' data. My expectation that is the case here

That is my suspicion, too.

> Also note that the underlying library does support IFCPARAMETERVALUE for IfcClothoid, however recognizes corner cases and handles them differently

What threshold value do you recommend to distinguish between "normal" and "corner" cases? It looks like at some threshold value, the IFCPARAMETERVALUE is taken to be a curve length rather than a true parameter. I'd like to have IfcOpenShell be consistent with other implementations. 

Perhaps there is a need for an implementer's agreement on this topics?

**Comment by peterrdf** [comment]
Looking closer at the file, it seems they use the Enrich application to populate geometry from business logic. I think a good idea, however they used an outdated version, if you know them please ask them to update to the latest sources (https://github.com/bSI-RailwayRoom/IFC-Rail-Unit-Test-Reference-Code/tree/master/EnrichIFC4x3).

If this is the case then every negative value is defined as IFCPARAMETERVALUE and the interpretation of parametrization is that it is 1-to-1 equal to the length measure. I know now we can define negative values for length measure and we now have clear parametrization, at least for Arc, Line and Clothoid, but back then it was a solution to create valid files against the schema (RC4 or 4.3.0.0 I believe),.

Our internal change for IfcClothoid is absolute value 7:
- absolute value of parametr is larger then or equal to 7 => parameterization 1-to-1 the length value, i.e. length = parameter
- if smaller then 7: length = parameter * clothoidConstant * sqrt(Pi)

Personally I think we should remove this from our solution as it creates confusion. Back then it had a proper use but now it will onl;y generate questions and the schema is stable now. I propose to remove it from our solution early October.

**Comment by RickBrice** [comment]
Thanks @peterrdf. I will refer the person with the file to this thread (I don't know who they are) and will leave IfcOpenShell implementation as is because it seems to be correct.
