### ISSUE TITLE
Document georeferencing additions

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/IFC4.x-IF#17]
As discusses in the IF meetings, please review and integrate the [proposed improvements to the documentation](https://github.com/buildingSMART/IFC4.x-IF/blob/main/docs/georeferencing%20additions/README.md) of the georef entities, used by the [latest examples](https://github.com/buildingSMART/IFC4.x-IF/tree/main/IFC-files/Georeferencing).

**Comment by LeeGregory12d** [comment]
Evandro,
Sorry but I have been out of action for a while.

In the given diagram, I don't understand what the box with [longitude, latitude and ellipsoid height] in it means?

**Comment by evandroAlfieri** [comment]
I've started editing the documentation, as per the to-do list below. Let me know if you have corrections.
 
- [x] [update documentation of IfcCoordinateOperation](https://github.com/buildingSMART/IFC4.3.x-development/compare/master...IF_georef-additions-docs)
- [ ] update documentation of  IfcCoordinateReferenceSystem
- [ ] update documentation of  IfcProjectedCRS
- [ ] Add CT (concept template) for IfcWellKnownText usage

**Comment by evandroAlfieri** [comment]
Obsolete issue. Track https://github.com/buildingSMART/IFC4.3.x-development/tree/IF_georef_documentation for documentation of the georeferencing additions

**Comment by pjanck** [comment]
> Track https://github.com/buildingSMART/IFC4.3.x-development/tree/IF_georef_documentation for documentation of the georeferencing additions

The link is dead:

![grafik](https://github.com/buildingSMART/IFC4.x-IF/assets/59165496/78daf997-f826-49b4-a852-9654fb7bb742)

Is there an alternative that one can track?

**Comment by evandroAlfieri** [comment]
Documentation of new and existing entities related to georeferencing is currently under review by the ISO Editorial Group. Will be published soon, as result of the review process. Keep an eye on https://github.com/buildingSMART/IFC4.3.x-development/commits/master
