### ISSUE TITLE
Update IfcSectionSolidHorizontal example to IFC4.3

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/IFC4.x-IF#2]
Current example (IFC4.3_RC3): https://github.com/bSI-InfraRoom/IFC-infra-unit-test/tree/main/FixedReferenceSweptAreaSolid-1

New version to be uploaded here: https://github.com/buildingSMART/IFC4.x-IF/tree/main/IFC-files

**Comment by michelangelo-acca** [comment]
Done by manually editing it. It seems that the only change is in the number of parameters for Alignment Horizontal, but please double check it if possible.

Also, in the same repository where you found this one, in the pull requests, you can find others which builds up complexity (i.e. rotated profiles, etc.) while keeping the test only for the sweep concept.

[FixedReferenceSweptAreaSolid-1.zip](https://github.com/buildingSMART/IFC4.x-IF/files/9535202/FixedReferenceSweptAreaSolid-1.zip)

**Comment by evandroAlfieri** [comment]
Thanks @michelangelo-acca . I've added this first test (and all the others you had in the Infra repository), to the official Forum repository. https://github.com/buildingSMART/IFC4.x-IF/tree/main/tests

P.S. we might need to do some minor changes to the rest of the files too. We'll see in the next meeting, and eventually open a new task. For the moment I consider this one done. Thanks again!
