### ISSUE TITLE
Alignment to use distinct nesting for its layouts and its referents

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/IFC4.x-IF#21]
**Problem**
Alignment can have a nesting relationship with: a) its layouts[Horizontal, Vertical, Cant], b) one or more Referents.
There is a doubt if the alignment's layouts and the referents must use the same nesting relationship or two distinct relationships.

**Solution(s)**
When Alignment nests some Referents, these must use another instance of `IfcRelNests`. In other words, they cannot be in the LIST containing the Alignment's layouts.

**Require schema changes?**
- ` ` yes
- `✓` no
- ` ` don't know

**Require documentation changes?**
- ` ` yes
- ` ` no
- `✓` don't know

**Rule required**
*Need for a formal rule? Describe it*
- `✓` normative check: every IFC file must pass this check
- ` ` good practice check: just triggers a warning, but the IFC file is still valid
- ` ` don't know

**Comment by SergejMuhic** [comment]
Typically, one relationship would feature a sequence of same types. I thought this is well established in bSI and software vendors.

**Comment by evandroAlfieri** [comment]
@SergejMuhic something like this?
```
#10= IFCALIGNMENT('1KYng3M_54wvOX6rrZauRU',$,'Name',$,$,#54,$,$);
#11= IFCALIGNMENTHORIZONTAL('3AW4bqoGrEbAZAADTqcHq8',$,'Name',$,$,#56,#61);
#12= IFCALIGNMENTVERTICAL('16kgZHIkHEd9yv74xmgfZP',$,'Name',$,$,#56,#66);
#200= IFCREFERENT('3AY4bqoGrEbAMKKDTqcHq8',$,'Name',$,$,$,$,.REFERENCEMARKER.);
#300= IFCREFERENT('5KL4ggoGrEbAMKKDTqcHq8',$,'Name',$,$,$,$,.REFERENCEMARKER.);
#400= IFCREFERENT('8PP6dftGrEbAMKKDTqcHq8',$,'Name',$,$,$,$,.REFERENCEMARKER.);

/* One relationship nesting alignment layouts in the alignment */
#90= IFCRELNESTS('1yHaBIo2T6qBWCXhdCktBu',$,$,$,#10,(#11,#12));

/* Another relationship nesting referents in the alignment */
#100= IFCRELNESTS('2zoYEuuQz7rPZaTdZMDitj',$,$,$,#10,(#200,#300,#400));
```

**Comment by SergejMuhic** [comment]
Even further, a separate `IfcRelNests` for `IfcAlignmentVertical` and `IfcAlignmentHorizontal` also.

**Comment by evandroAlfieri** [comment]
All example files that vendors produced so far have the horizontal, vertical, cant layouts all listed in one relationship. Why the suggestion of splitting them?

**Comment by SergejMuhic** [comment]
Two reasons:
1. as stated here

> Typically, one relationship would feature a sequence of same types.

this was sort of how relationships were used.

2. It makes for unambiguous single type sequences where you can write simpler rules such as: "Type of `RelatedTypes` is `IfcAlignmentVertical`" for example. It is doable in both ways of course, it is just a bit cleaner.

**Comment by evandroAlfieri** [comment]
> ... a sequence of same types.
Doesn't really apply for alignment, does it? If I remember well, from business point of view, each alignment can have only 1 Horizontal component, 0 or 1 Vertical, 0 or 1 Cant. There will never be an alignment with "a sequence of horizontal layout". That would be multiple alignments

**Comment by SergejMuhic** [comment]
The sequence is IfcRelNests.RelatedObject L[1:?].

**Comment by evandroAlfieri** [comment]
Precisely, and for Alignment the sequence (in all examples collected so far) is: the horizontal component, the vertical, sometimes the cant. If I understood correctly, you're suggesting to separate these components in 3 different relationships. But in this case the IfcRelNests.RelatedObjects L[1:?] list would contain just one element, which makes the sequence...well, not a sequence.

**Comment by SergejMuhic** [comment]
A sequence with one element is still a sequence. Here some examples:
1. one `IfcSite` in `IfcProject`,
2. one `IfcTriangulatedFaceSet` in `IfcShapeRepresentation.Items`,
3. one `IfcShapeRepresentation` in `IfcProductDefinitionShape`

There are many more examples but we should be precise in the scope of the discussions. Data model vs instantiation of the model, template vs occurrence ...

Why I say cleaner is the a rule saying "Type of `RelatedTypes` is `IfcAlignmentVertical`" vs "Type of `RelatedTypes` is List of `IfcAlignmentHorizontal`, `IfcAlignmentVertical` and `IfcAlignmentCant`". Comparing these two and how to write rules, IMHO first one is much cleaner. The second one is missing a lot more words to make it clear (one instance?, all of them always or only two still okay? etc.)

**Comment by aothms** [comment]
> Typically, one relationship would feature a sequence of same types.

This should only apply to some level in the subtyping hierarchy though. Thinking of the typical aggregation scenario, composing a compound wall of IfcBuildingElementPart, IfcCovering, IfcMember, ... We'd also expect the same relationship node to be used. I'd say because they are all IfcBuilding/tElement. At least this is the current approach in software.

The same applies here, it makes sense to group {IfcAlignmentHorizontal -Vertical and -Cant} being all IfcLinearElement. IfcReferent is further away in the schema hierarchy, so could be further away.

On the other hand, I want to reiterate to also keep in mind more modern graph databases where it's more natural to think of the objectified relationship as the type/colour of an edge, and maintaining this kind of grouping as a hard requirement is cumbersome.

**Comment by SergejMuhic** [comment]
I am trying not to talk in absolutes and list the benefits it would bring. Currently, a new relationship occurrence is used depending on the usage rather than the place in the 

> schema hierarchy

It would be quite arbitrary to define a "place in the schema hierarchy".

Not to diverge from the issue just a short clarification, my consideration was based more on the project structure type of decomposition e.g. Building - Building Storey since alignment is closer to that kind of a composition that an actual physical element assembly.

We probably should stick to the issue and discuss the reasoning whether or not it makes sense. What do you mean with

> and maintaining this kind of grouping as a hard requirement is cumbersome.

Especially the "cumbersome" part. What does that mean in your view? Focusing on data exchange or implementation in software, data archiving etc.?

I cannot decipher which one you would prefer and for what kind of use case.

**Comment by aothms** [comment]
> Especially the "cumbersome" part. What does that mean in your view?

In a graph representation of nodes and edges, node being alignment and segment, edge being the nesting relationship. You'll need additional indirections (i.e the objectified relationship) to represent this kind of grouping. These indirections are costly wrt to computational complexity and ease of understanding. In general, the more weight and requirements you give to (in most scenarios) transient concepts such as relationship nodes (i.e they don't exist as objectified relationships in the domain model of the native software so have to be generated at export), the more difficult it gets to comply. In federation use cases, they also need additional care given some of the cardinality constraints. In the IFC5 working group they were pretty close to suggesting to use direct attributes (a single Parent reference) for the predominant decomposition/containment tree (the distinction we're discussing here would have become irrelevant). I'm just saying that the strong preference for objectified relationships is not something universally shared and, while I personally have nothing against them, I would limit the amount of specific requirements and semantics given to them.

> It would be quite arbitrary to define a "place in the schema hierarchy".

What we were discussing here were sibling types {IfcAlignmentHorizontal -Vertical and -Cant} vs non-sibling types (IfcReferent to others).

**Comment by SergejMuhic** [comment]
Thanks for the clarification but I am looking at the state-of-the-art and not future standards that might follow a certain direction or they might not. I am focusing on IfcAlignment layout in IFC4X3 (I hope in IFC5 it can be completely redone actually). I can go either way, but the discussion should be on the actual pros and cons. My preference leans towards three relationships (I think my reasoning on that was clear, I have yet to hear a counter argument for it) but I can understand the argument for one relationship also.

Oh, yes we can agree that additional objectified relationships are costly, but why would you even consider interpreting them as own nodes? Flattening the structure is not forbidden.

That being said, there are many other use cases where you would want a clean relationship with only one type in the collection. I cannot imagine (even with the sibling logic) that it would make sense to put the siblings underneath `IfcSpatialStructureElement` into one `IfcRelAggregates`.

**Comment by evandroAlfieri** [comment]
Thanks all for your input. Due to unclear requirements + low interest from implementers, I'm closing this until further notice.
