### ISSUE TITLE
IfcMapConversion used for the geometric context of an IfcAlignment

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/IFC4.x-IF#22]
I am unsure about the validity of data. Using `IfcMapConversion` with `IfcProjectedCRS` means that the coordinates of the geometric context are to be understood as true-to-the-size with reality. I doubt that the `IfcAlignment` has true dimensions. Can you please double check, @evandroAlfieri ?

https://github.com/buildingSMART/IFC4.x-IF/blob/33735e64e08f03d8eaeab57e70bc77cf5c06d1ed/IFC-files/Georeferencing/Georeferencing_COMPDCS(WKT)-MC.ifc#L20
https://github.com/buildingSMART/IFC4.x-IF/blob/33735e64e08f03d8eaeab57e70bc77cf5c06d1ed/IFC-files/Georeferencing/Georeferencing_COMPDCS(WKT)-MC.ifc#L30
https://github.com/buildingSMART/IFC4.x-IF/blob/33735e64e08f03d8eaeab57e70bc77cf5c06d1ed/IFC-files/Georeferencing/Georeferencing_COMPDCS(WKT)-MC.ifc#L199
https://github.com/buildingSMART/IFC4.x-IF/blob/33735e64e08f03d8eaeab57e70bc77cf5c06d1ed/IFC-files/Georeferencing/Georeferencing_COMPDCS(WKT)-MC.ifc#L431
https://github.com/buildingSMART/IFC4.x-IF/blob/33735e64e08f03d8eaeab57e70bc77cf5c06d1ed/IFC-files/Georeferencing/Georeferencing_COMPDCS(WKT)-MC.ifc#L432
https://github.com/buildingSMART/IFC4.x-IF/blob/33735e64e08f03d8eaeab57e70bc77cf5c06d1ed/IFC-files/Georeferencing/Georeferencing_COMPDCS(WKT)-MC.ifc#L911
https://github.com/buildingSMART/IFC4.x-IF/blob/33735e64e08f03d8eaeab57e70bc77cf5c06d1ed/IFC-files/Georeferencing/Georeferencing_COMPDCS(WKT)-MC.ifc#L912

**Comment by evandroAlfieri** [comment]
Reading #19 I understand this specific examples doesn't make sense. Alignment data are already in map meters, so IfcMapConversion should not be used. I'll remove the example and leave only the one with IfcRigidOperation.
Thanks @pjanck

**Comment by evandroAlfieri** [comment]
That means also this example is to be removed, right @pjanck ? [Georeferencing_COMPDCS(EPSG)-MC.ifc](https://github.com/buildingSMART/IFC4.x-IF/blob/main/IFC-files/Georeferencing/Georeferencing_COMPDCS(EPSG)-MC.ifc)

**Comment by pjanck** [comment]
> That means also this example is to be removed

I cannot say, since I wasn't present when the data was produced. 

> I am unsure about the validity of data.

I would ask the actor responsible for the data, as to what their intention was.

**Comment by evandroAlfieri** [comment]
Wrong examples removed
