### ISSUE TITLE
Update or remove IFC 4.3 sample files in Sample-Test-File

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/IFC4.x-IF#3]
See https://github.com/buildingSMART/Sample-Test-Files/tree/master/IFC%204.3

**Comment by evandroAlfieri** [comment]
As discussed, since some files are from @LeeGregory12d , I'm co-assigning him to this task - so he can help @peterrdf updating old files that have georeferencing entities in there

**Comment by LeeGregory12d** [comment]
We need to wait until we know if Stefan and Sergej new changes happen

**Comment by evandroAlfieri** [comment]
ping to @peterrdf and @LeeGregory12d to update to latest schema or remove files in the Sample-Test-File repository. Thanks

**Comment by LeeGregory12d** [comment]
Evandro
Do we have a final version of 4x3?
Did it include the georeferencing changes put forward by Sergej?



Regards

Dr Lee Gregory
Managing Director
12d Solutions Pty Ltd

Web www.12d.com<http://www.12d.com>
Email ***@***.***
________________________________

**Comment by evandroAlfieri** [comment]
@LeeGregory12d
Latest schema is extracted here: https://github.com/buildingSMART/IFC4.x-IF/blob/main/docs/schema-diffs/IFC4X3_ADD1.exp
Full documentation available here: http://ifc43-docs.standards.buildingsmart.org/
They include georeferencing part. (Documentation might need improvement on georeferencing additions)

**Comment by LeeGregory12d** [comment]
Thanks Evandro
