### ISSUE TITLE
Query on test file length measure

### ISSUE THREAD

**Issue by jmirtsch** [buildingSMART/IFC4.x-IF#59]
https://github.com/buildingSMART/IFC4.x-IF/blob/75010aa8b26cdd6b980f47cba218ad940d411fab/tests/STN01/test-output/ACCA/STN01_ACCA.ifc#L2581C19-L2581C19

#2574 = IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE., #2577, IFCNONNEGATIVELENGTHMEASURE(23511.9465684978), IFCNONNEGATIVELENGTHMEASURE(49.9983334328186), #2578);

IFCNONNEGATIVELENGTHMEASURE(23511.9465684978) looks like an invalid length measure.  The segment is roughly 50m long.
Let me know if I'm misunderstanding this.

**Comment by peterrdf** [comment]
Hi Jon, to me it looks correct. Looking at the semantic definition (business logic) we have a segment based on:
#2380 = IFCALIGNMENTVERTICALSEGMENT($, $, 778.005739095076, 49.9975001869751, 2.24998125155613, -9.99999999989088E-3, 4.24043141700466E-15, 5000., .CIRCULARARC.);

Lets say a circle part that ends at the bottom of a complete circle and has an anit-clockwise direction. so it ends at 1.5 * Pi * 5000 what is exactly above SegmentStart + SegmentLength. Also SegmentLength is a fraction larger than vertical length as expected.

Maybe here it would be better to use parameter values, however I think with the latest proposals I maybe should change it into:
#2574 = IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE., #2577, IFCLENGTHMEASURE(-7903.9799674), IFCLENGTHMEASURE(49.9983334328186), #2578);

**Comment by jmirtsch** [comment]
Hi Peter,

Thanks for the clarification.  Based on your response, I reviewed my support of this scenario and did find an issue.  The value is fine and I will close the issue.

**Comment by michelangelo-acca** [comment]
Well, the only thing I can say is thanks to @jmirtsch for spotting a possible issue and thanks to @peterrdf for providing the solution / explanation!
